blank_issues_enabled: false
contact_links:
  - name: 💬 Questions / Help
    url: https://stackoverflow.com/
    about: If you have questions, please check https://www.i18next.com/ or https://react.i18next.com/ or https://stackoverflow.com/ or similar.